name: "✨ Feature Request"
description: "提出新功能/增强需求"
title: "[Feature] "
labels: ["type/feature", "status/triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: 模块（Area）
      options:
        - backend
        - frontend
        - acp-proxy
        - infra
        - docs
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级（Priority）
      options:
        - P0（必须）
        - P1（应该）
        - P2（可选）
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景与目标
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 需求范围（Scope）
      placeholder: |
        - 包含：
        - 不包含：
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准（Acceptance Criteria）
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
